#!/usr/bin/env python

import csv

def gender_correlation():
    defaults = 0
    men = 0
    women = 0
    f = open('training_set.csv', 'rb')
    a = 0
    reader = csv.reader(f)
    for row in reader:
        if a <= 1:
            a += 1
        else:
            val = int(row[24])
            if int(row[2]) == 1:
                men += val
                defaults += val
            else:
                women += val
                defaults += val
           # print "Gender is " + str(row[2]) + " and default: " + str(row[24])
    print "Men: " + str(men)
    print "Women: " + str(women)
    print "Total Defaults: " + str(defaults)
    f.close()

def education_correlation():
    defaults = 0
    grad = 0
    college = 0
    high = 0
    other = 0
    f = open('training_set.csv', 'rb')
    a = 0
    reader = csv.reader(f)
    for row in reader:
        if a <= 1:
            a += 1
        else:
            val = int(row[24])
            check = int(row[3])
            if check == 1:
                grad += val
                defaults += val
            elif check == 2:
                college += val
                defaults += val
            elif check == 3:
                high += val
                defaults += val
            elif check == 4:
                other += val
                defaults += val
            else:
                print "Unexpected education value"
                return
    print "Grad: " + str(grad)
    print "Undergrad: " + str(college)
    print "High School: " + str(high)
    print "Other: " + str(other)
    print "Total Defaults " + str(defaults)\
    f.close()

gender_correlation()
education_correlation()
